export const coins = [
  '14 AYAR',
  '22 AYAR',
  'ALTIN GÜMÜŞ',
  'ESKİ ATA',
  'ESKİ ATA5',
  'ESKİ ÇEYREK',
  'ESKİ GREMSE',
  'ESKİ TAM',
  'ESKİ YARIM',
  'EUR/KG',
  'GRAM ALTIN',
  'GÜMÜŞ ONS',
  'GÜMÜŞ TL',
  'GÜMÜŞ USD',
  'Has Altin',
  'ONS',
  'PALADYUM ONS',
  'PALADYUM USD',
  'PLATİN ONS',
  'PLATİN USD',
  'USD/KG',
  'YENİ ATA',
  'YENİ ATA5',
  'YENİ ÇEYREK',
  'YENİ GREMSE',
  'YENİ TAM',
  'YENİ YARIM',
];
